<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="Content-Language" content="pt-Br">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no" />

	<link rel="stylesheet" type="text/css" href="<?= assets('css/style.css'); ?>">
	<script type="text/javascript" src=<?= assets("js/jquery-3.2.1.slim.min.js") ?> ></script>
	<script type="text/javascript" src=<?= assets("js/jquery.maskedinput.min.js") ?> ></script>  
	<script type="text/javascript" src=<?= assets("js/vue.js") ?> ></script>  
	
	<link href="<?= assets('css/font-awesome.min.css'); ?>" rel="stylesheet" >
	<title>Signo Web</title>
	<link rel="SHORTCUT ICON" href="<?= assets('img/favicon.ico')?>">
</head>
<body>
	<header>
		<h1 class="float-l">
			<a href="<?= url('/') ?>" title="Titulo do Site">Signo - Enquetes</a>
		</h1>
		
		<input type="checkbox" id="control-nav" />
		<label for="control-nav" class="control-nav"></label>
		<label for="control-nav" class="control-nav-close"></label>

		<nav class="float-r">
			<ul class="list-auto">
				<li>
				<a href="<?= url('/') ?>" title="Início">Início</a>
				</li>
				<li>
				<a href="<?= url('/nova') ?>" title="Nova Enquete">Nova Enquete</a>
				</li>
				<li>
				<a href="<?= url('/enquetes/editar') ?>" title="Editar Enquetes">Editar Enquetes</a>
				</li>
			</ul>
		</nav>
	</header>

	<section id="">
		<?= $this->yieldView(); ?>
	</section>

</body>

</html>
