<div class="container">  
    <form action="#" class="form-contact" method="post" tabindex="1">  
        <label for="">Título</label>
        <input type="text" class="form-contact-input" name="titulo" placeholder="Título" required />
        <label for="">Data de Início</label>  
        <input type="date" class="form-contact-input" name="dta_inicio"  required />
        <label for="">Data de Encerramento</label>  
        <input type="date" class="form-contact-input" name="dta_fim" required/>  
        <button type="submit" class="form-contact-button">Enviar</button>  
    </form>  
</div>  