<div class="band">
    <? foreach($this->enquetes as $enquete){ ?>
    <div class="item-3">
        <a href="<?= url("/enquete/{$enquete->id}") ?>" class="card">
            <div class="thumb" style="background-image: url(/app/Public/img/enquete.jpg);"></div>
            <article>
                <h1><?= $enquete->titulo ?></h1>
                <label class="f-s-12">
                <? 
                if($enquete->data_inicio > date('Y-m-d')){ ?>
                    <strong class="aguardando">Aguardando abertura</strong>
                <? 
                }elseif ($enquete->data_fim > date('Y-m-d')){
                ?>
                    <strong class="aberta">Aberta</strong>
                <? }else { ?>
                    <strong class="encerrada" >Encerrada</strong>
                <? } ?>
                </label> <br>
                <span><?= dateFormated($enquete->data_inicio, 'd/m/y').' a '.dateFormated($enquete->data_fim, 'd/m/y')?></span>
            </article>
        </a>
    </div>
    <? } ?>
    
</div>

<style>

</style>