<div class="band">
    <div class="item-3">
        <a href="" class="card">
            <div class="thumb" style="background-image: url(/app/Public/img/enquete.jpg);"></div>
            <article>
                <h1>Enquete</h1>
                <p>sadasdasdaddasdd d asd a d ad a d ad a d ad as d as das d</p>
                <span>Data de inicio e fim</span>
            </article>
        </a>
    </div>
    <div class="item-3">
        <a href="" class="card">
            <div class="thumb" style="background-image: url(/app/Public/img/enquete.jpg);"></div>
            <article>
                <h1>Enquete</h1>
                <p>sadasdasdaddasdd d asd a d ad a d ad a d ad as d as das d</p>
                <span>Data de inicio e fim</span>
            </article>
        </a>
    </div>
    <div class="item-3">
        <a href="" class="card">
            <div class="thumb" style="background-image: url(/app/Public/img/enquete.jpg);"></div>
            <article>
                <h1>Enquete</h1>
                <p>sadasdasdaddasdd d asd a d ad a d ad a d ad as d as das d</p>
                <span>Data de inicio e fim</span>
            </article>
        </a>
    </div>
    <div class="item-3">
        <a href="" class="card">
            <div class="thumb" style="background-image: url(/app/Public/img/enquete.jpg);"></div>
            <article>
                <h1>Enquete</h1>
                <p>sadasdasdaddasdd d asd a d ad a d ad a d ad as d as das d</p>
                <span>Data de inicio e fim</span>
            </article>
        </a>
    </div>
    <div class="item-3">
        <a href="" class="card">
            <div class="thumb" style="background-image: url(/app/Public/img/enquete.jpg);"></div>
            <article>
                <h1>Enquete</h1>
                <p>sadasdasdaddasdd d asd a d ad a d ad a d ad as d as das d</p>
                <span>Data de inicio e fim</span>
            </article>
        </a>
    </div>
</div>