<div class="band">
    <? foreach($this->enquetes as $enquete){ ?>
    <div class="item-3">
        <a href="<?= url("/enquete/{$enquete->id}") ?>" class="card">
            <div class="thumb" style="background-image: url(/app/Public/img/enquete.jpg);"></div>
            <article>
                <h1><?= $enquete->titulo ?></h1>
                <!-- <p>sadasdasdaddasdd d asd a d ad a d ad a d ad as d as das d</p> -->
                <span>Data de inicio e fim</span>
            </article>
        </a>
    </div>
    <? } ?>
    
</div>